XCODE_USER_COLOR_PALLETES_DIR=~/Library/Colors

install:
	rm -fR $(XCODE_USER_TEMPLATES_DIR)/OASIS
	rm -fR $(XCODE_USER_COLOR_PALLETES_DIR)/OASIS.clr
	cp -R Xcode/OASIS.clr $(XCODE_USER_COLOR_PALLETES_DIR)

uninstall:
	rm -fR $(XCODE_USER_COLOR_PALLETES_DIR)/OASIS.clr
